blank_issues_enabled: false
contact_links:
  - name: Let's Discuss on Github
    url: https://github.com/Faq/Truice-FMX/discussions
    about: Nothing to report, but have suggestion or question?
  - name: Discord server
    url: https://discord.gg/HPP3wNh
    about: Have urgent questions, lets talk on Discord
